### ISSUE TITLE
Error handling exceptions in CSV upload

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#345]
1. Edit the first row of dummy_sheet.csv
2. Change Date of Birth to remove the year from the date (cause an invalid value)
3. Upload it

*Expected*:

- You get an error in the user interface
- All but the first rows are processed

*Actual*:

- You get an unhandled Django error (see below)
- You don't see any patients

```
django-1   | Traceback (most recent call last):                                                                                                                                                                    django-1   |   File "/app/project/npda/views/home.py", line 64, in home                                                                                                                                            django-1   |     await csv_upload(
django-1   |   File "/app/project/npda/general_functions/csv_upload.py", line 329, in csv_upload
django-1   |     await patient.asave()                                                                                                                                                                             django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 922, in asave
django-1   |     return await sync_to_async(self.save)(                                                                                                                                                            django-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                            django-1   |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 468, in __call__
django-1   |     ret = await asyncio.shield(exec_coro)
django-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/asgiref/current_thread_executor.py", line 40, in run
django-1   |     result = self.fn(*self.args, **self.kwargs)
django-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                       django-1   |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 522, in thread_handler
django-1   |     return func(*args, **kwargs)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
django-1   |     self.save_base(
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base                                                                                                     django-1   |     updated = self._save_table(
django-1   |               ^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1160, in _save_table
django-1   |     results = self._do_insert(                                                                                                                                                                [44/809]django-1   |               ^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1201, in _do_insert
django-1   |     return manager._insert(
django-1   |            ^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
django-1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
django-1   |     return query.get_compiler(using=using).execute_sql(returning_fields)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1835, in execute_sql
django-1   |     for sql, params in self.as_sql():
django-1   |                        ^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1760, in as_sql
django-1   |     self.prepare_value(field, self.pre_save_val(field, obj))
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1699, in prepare_value
django-1   |     return field.get_db_prep_save(value, connection=self.connection)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
django-1   |     return self.get_db_prep_value(value, connection=connection, prepared=False)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1536, in get_db_prep_value
django-1   |     value = self.get_prep_value(value)
django-1   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1531, in get_prep_value
django-1   |     return self.to_python(value)
django-1   |            ^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1497, in to_python
django-1   |     raise exceptions.ValidationError(
django-1   | django.core.exceptions.ValidationError: ['“26/10/” value has an invalid date format. It must be in YYYY-MM-DD format.']
django-1   |
django-1   | During handling of the above exception, another exception occurred:
django-1   |
django-1   | Traceback (most recent call last):
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
django-1   |     response = get_response(request)
django-1   |                ^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
django-1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 254, in __call__
django-1   |     return call_result.result()
django-1   |            ^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
django-1   |     return self.__get_result()
django-1   |            ^^^^^^^^^^^^^^^^^^^
django-1   |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
django-1   |     raise self._exception
django-1   |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 331, in main_wrap
django-1   |     result = await self.awaitable(*args, **kwargs)
django-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/app/project/npda/views/decorators.py", line 52, in async_login_and_otp_required
django-1   |     response = await view(request, *args, **kwargs)
django-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django-1   |   File "/app/project/npda/views/home.py", line 85, in home
django-1   |     errors = error_list(error)
django-1   |              ^^^^^^^^^^^^^^^^^
django-1   |   File "/app/project/npda/views/home.py", line 33, in error_list
django-1   |     for field, errors in wrapper_error.error_dict.items():
django-1   |                          ^^^^^^^^^^^^^^^^^^^^^^^^
django-1   | AttributeError: 'ValidationError' object has no attribute 'error_dict'. Did you mean: 'error_list'?
```

**Comment by mbarton** [comment]
Originally reported here with a visit field rather than a patient field: https://github.com/rcpch/national-paediatric-diabetes-audit/pull/341#issuecomment-2447877749

I think the problem is that processing the row with the form issues a validation error but we still keep the value in the model, which triggers another ValidationError during Model.save. This error doesn't include which field has caused the issue, so therefore doesn't have error_dict. The processing code then crashes.

There's probably multiple things to fix here:

- The top level code gathering ValidationError should not crash if it doesn't have per-field errors
- We should catch ValidationErrors from save and attach row numbers before re-raising them
  - They also shouldn't fail the entire upload? We would need to clearly indicate though that only part of the upload succeeded, so probably one for another issue
- We should remove invalid fields from the model before saving
  - We need to be nuanced here though as it may have failed validation but still fits in the database type correctly
  - Perhaps something as silly as "try to save, catch error, remove field, try again" would work?
  - Or perhaps manually call `to_python` on the field and remove those that fail. If one fails in a required field, we can't save the patient at all (we currently catch this by looking for `error.code in ["required", "null"]` which always felt flakey
